#!/usr/bin/env bun
/**
 * Renders the react-email templates to a committed TypeScript module.
 *
 *   bun run email:build
 *
 * Why build time: react, react-dom and @react-email/* are devDependencies. The
 * serverless function imports plain strings, so React is never in its bundle.
 *
 * Why a .ts module rather than .html files: SvelteKit bundles the function from
 * the module graph, so an imported string is picked up automatically. Reading
 * HTML from disk at runtime would depend on Vercel's file tracing, which is the
 * fragile option.
 *
 * The output is committed for the same reason the resume PDFs are: Vercel runs
 * `vite build` and nothing else, so nothing regenerates it there.
 *
 * Bun runs this .tsx directly, which is why there is no esbuild or JSX config.
 */
import { render } from '@react-email/render';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as React from 'react';

import { Confirmation } from '../emails/Confirmation.js';
import { Notification } from '../emails/Notification.js';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'src', 'lib', 'server', 'email');
const outFile = join(outDir, 'templates.ts');

const templates = [
	{
		key: 'confirmation',
		subject: 'Thanks for getting in touch',
		element: <Confirmation />
	},
	{
		key: 'notification',
		subject: 'New message from the site',
		element: <Notification />
	}
] as const;

/** Embeds a rendered string as a TS template literal without letting it break out. */
function quote(value: string): string {
	return '`' + value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

const parts: string[] = [];

for (const { key, subject, element } of templates) {
	const html = await render(element);
	// Same tree, so the plaintext alternative cannot drift from the HTML. The old
	// confirmation had no text part at all, which is a spam-score negative and
	// unreadable in text-only clients.
	const text = await render(element, { plainText: true });

	if (!html.includes('<table')) {
		throw new Error(`${key}: rendered without a table layout, which Outlook needs`);
	}

	parts.push(
		`export const ${key} = {\n` +
			`\tsubject: ${JSON.stringify(subject)},\n` +
			`\thtml: ${quote(html)},\n` +
			`\ttext: ${quote(text)}\n` +
			`} as const;`
	);
}

const banner = `/**
 * GENERATED by scripts/build-emails.tsx — do not edit.
 *
 * Source templates live in emails/. Run \`bun run email:build\` after changing
 * them, and commit the result: Vercel only runs \`vite build\`.
 */
/* eslint-disable */`;

await mkdir(outDir, { recursive: true });
await writeFile(outFile, `${banner}\n\n${parts.join('\n\n')}\n`, 'utf8');

console.log(`wrote ${outFile}`);
for (const { key } of templates) console.log(`  ${key}`);
